export const content = {
  fr: {
    skip: "Aller au contenu",
    nav: { approach: "Approche", expertise: "Expertises", method: "Méthode", brief: "Votre projet" },
    menu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    navLabel: "Navigation principale",
    language: "English",
    languageCode: "EN",
    eyebrow: "Événementiel premium · privé & professionnel",
    title: "Le moment devient signature.",
    lead: "Purple Events transforme une intention en expérience cohérente, sensible et précisément orchestrée.",
    primaryCta: "Construire mon brief",
    secondaryCta: "Découvrir l’approche",
    highlights: ["Direction créative", "Coordination", "Production"],
    approachEyebrow: "Notre approche",
    approachTitle: "Bien plus qu’un décor. Une direction.",
    approachText: "Nous relions esthétique, rythme et logistique pour que chaque décision serve le même récit — le vôtre.",
    principles: [
      { number: "01", title: "Clarté", text: "Un cadre lisible, des arbitrages expliqués et un pilotage sans zones grises." },
      { number: "02", title: "Singularité", text: "Une identité construite autour du projet, jamais un événement copié-collé." },
      { number: "03", title: "Maîtrise", text: "Chaque détail est replacé dans une vision d’ensemble, du premier échange au jour J." },
    ],
    expertiseEyebrow: "Expertises",
    expertiseTitle: "Une vision. Trois disciplines.",
    expertiseText: "Le périmètre final s’adapte au projet et se précise lors du cadrage.",
    services: [
      { index: "01", title: "Direction artistique & scénographie", text: "Concept, langage visuel, matières, lumière et mise en espace : une identité sensible et cohérente." },
      { index: "02", title: "Production & coordination", text: "Planning, prestataires, flux et temps forts sont articulés dans un dispositif clair et réaliste." },
      { index: "03", title: "Expérience invités", text: "Accueil, rythme, circulation et attentions : l’événement est pensé depuis le point de vue de celles et ceux qui le vivent." },
    ],
    methodEyebrow: "Méthode",
    methodTitle: "Du premier échange au dernier instant.",
    steps: [
      { step: "Cadrer", text: "Objectifs, format, contraintes, calendrier et enveloppe de référence." },
      { step: "Concevoir", text: "Direction créative, expérience, scénario et choix structurants." },
      { step: "Produire", text: "Organisation, coordination des intervenants et validation des détails." },
      { step: "Orchestrer", text: "Pilotage opérationnel et continuité de l’expérience le jour J." },
    ],
    briefEyebrow: "Votre projet",
    briefTitle: "Commençons par l’essentiel.",
    briefText: "Quelques repères suffisent pour préparer un premier échange utile.",
    form: {
      type: "Type d’événement",
      typePlaceholder: "Choisir un format",
      typeOptions: ["Célébration privée", "Événement de marque", "Rencontre professionnelle", "Autre projet"],
      location: "Ville ou destination envisagée",
      locationPlaceholder: "Ville ou lieu envisagé",
      date: "Période ou date",
      datePlaceholder: "Ex. septembre 2027",
      guests: "Nombre d’invités estimé",
      guestsPlaceholder: "Ex. 120",
      name: "Votre nom",
      namePlaceholder: "Nom complet",
      email: "Votre e-mail",
      emailPlaceholder: "vous@exemple.com",
      message: "L’intention en quelques lignes",
      messagePlaceholder: "Ce que vous souhaitez faire ressentir, vos priorités et contraintes connues…",
      consentBefore: "J’ai pris connaissance de la ",
      consentLink: "politique de confidentialité",
      consentAfter: " et je confirme que ces informations peuvent être utilisées pour répondre à ma demande.",
      submitEndpoint: "Envoyer mon brief",
      submitEmail: "Préparer mon e-mail",
      submitCopy: "Copier mon brief",
      sending: "Envoi…",
      success: "Votre brief a bien été transmis.",
      emailReady: "Votre application e-mail va s’ouvrir avec le brief prérempli.",
      copied: "Brief copié. Vous pouvez le coller dans le canal de contact de votre choix.",
      error: "L’envoi n’a pas abouti. Votre texte reste intact : vous pouvez le copier et réessayer.",
      required: "Merci de renseigner les champs obligatoires et de confirmer la lecture de la politique de confidentialité.",
    },
    footerLine: "Direction créative · Coordination · Production",
    groupInitiative: "Une initiative Purple Orchid Group",
  },
  en: {
    skip: "Skip to content",
    nav: { approach: "Approach", expertise: "Expertise", method: "Method", brief: "Your project" },
    menu: "Open menu",
    closeMenu: "Close menu",
    navLabel: "Primary navigation",
    language: "Français",
    languageCode: "FR",
    eyebrow: "Premium events · private & professional",
    title: "A moment becomes a signature.",
    lead: "Purple Events turns an intention into a coherent, thoughtful and precisely orchestrated experience.",
    primaryCta: "Build my brief",
    secondaryCta: "Explore our approach",
    highlights: ["Creative direction", "Coordination", "Production"],
    approachEyebrow: "Our approach",
    approachTitle: "More than décor. A direction.",
    approachText: "We connect aesthetics, rhythm and logistics so every decision serves one narrative — yours.",
    principles: [
      { number: "01", title: "Clarity", text: "A readable framework, explained decisions and project steering with no grey areas." },
      { number: "02", title: "Singularity", text: "An identity shaped around the project, never a copy-and-paste event." },
      { number: "03", title: "Control", text: "Every detail belongs to the wider vision, from the first conversation to event day." },
    ],
    expertiseEyebrow: "Expertise",
    expertiseTitle: "One vision. Three disciplines.",
    expertiseText: "The final scope is shaped around the project and defined during discovery.",
    services: [
      { index: "01", title: "Creative direction & scenography", text: "Concept, visual language, materials, lighting and spatial design: one sensitive, coherent identity." },
      { index: "02", title: "Production & coordination", text: "Planning, suppliers, guest flows and key moments are brought together in a clear, realistic system." },
      { index: "03", title: "Guest experience", text: "Welcome, rhythm, movement and thoughtful details: the event is designed from the guest’s point of view." },
    ],
    methodEyebrow: "Method",
    methodTitle: "From the first conversation to the final moment.",
    steps: [
      { step: "Frame", text: "Objectives, format, constraints, timeline and reference budget." },
      { step: "Design", text: "Creative direction, experience, narrative and defining choices." },
      { step: "Produce", text: "Organisation, supplier coordination and detail validation." },
      { step: "Orchestrate", text: "Operational leadership and continuity of experience on event day." },
    ],
    briefEyebrow: "Your project",
    briefTitle: "Let’s start with what matters.",
    briefText: "A few useful details are enough to prepare a focused first conversation.",
    form: {
      type: "Event type",
      typePlaceholder: "Choose a format",
      typeOptions: ["Private celebration", "Brand event", "Professional gathering", "Another project"],
      location: "City or destination",
      locationPlaceholder: "City or intended venue",
      date: "Date or timeframe",
      datePlaceholder: "E.g. September 2027",
      guests: "Estimated guest count",
      guestsPlaceholder: "E.g. 120",
      name: "Your name",
      namePlaceholder: "Full name",
      email: "Your email",
      emailPlaceholder: "you@example.com",
      message: "Your intention in a few lines",
      messagePlaceholder: "What you want people to feel, your priorities and any known constraints…",
      consentBefore: "I have read the ",
      consentLink: "privacy policy",
      consentAfter: " and confirm that this information may be used to respond to my request.",
      submitEndpoint: "Send my brief",
      submitEmail: "Prepare my email",
      submitCopy: "Copy my brief",
      sending: "Sending…",
      success: "Your brief has been sent.",
      emailReady: "Your email app will open with the brief already prepared.",
      copied: "Brief copied. Paste it into the contact channel of your choice.",
      error: "The message could not be sent. Your text is intact: copy it and try again.",
      required: "Please complete the required fields and confirm that you have read the privacy policy.",
    },
    footerLine: "Creative direction · Coordination · Production",
    groupInitiative: "A Purple Orchid Group initiative",
  },
};
