export const legalContent = {
  fr: {
    previewBlocker: "Ces informations doivent être validées avant l’ouverture publique.",
    back: "Retour à l’accueil",
    language: "English",
    languageCode: "EN",
    privacy: {
      eyebrow: "Protection des données",
      title: "Politique de confidentialité",
      intro: "Cette politique décrit les traitements liés au site purpleevents.fun. Elle sera actualisée avant toute activation d’un nouvel outil de mesure, formulaire serveur ou service tiers.",
      sections: {
        controller: "Responsable du traitement",
        data: "Données et finalités",
        legalBasis: "Bases juridiques",
        recipients: "Destinataires",
        retention: "Conservation",
        rights: "Vos droits",
      },
      dataText: "Le formulaire prépare une demande comprenant, selon les champs remplis : type d’événement, lieu, période, nombre d’invités, nom, e-mail et message. En mode copie locale, aucune de ces données n’est transmise par le site. En mode e-mail, l’envoi est pris en charge par votre application de messagerie.",
      legalBasisText: "Les demandes sont traitées afin de répondre à votre sollicitation et, lorsque pertinent, de prendre des mesures précontractuelles. Les journaux techniques nécessaires à la sécurité reposent sur l’intérêt légitime à protéger le service.",
      recipientsText: "L’accès est limité aux personnes habilitées de Purple Events et, lorsque nécessaire, aux prestataires techniques d’hébergement, de sécurité et de messagerie agissant dans leur rôle respectif.",
      rightsText: "Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou l’opposition lorsque ces droits s’appliquent. Vous pouvez également introduire une réclamation auprès de la Commission nationale pour la protection des données du Luxembourg (CNPD).",
    },
    cookies: {
      eyebrow: "Transparence numérique",
      title: "Politique relative aux cookies",
      intro: "Purple Events n’installe aucun cookie publicitaire, outil analytique, pixel marketing ou contenu social embarqué dans cette version.",
      tableTitle: "Stockage fonctionnel utilisé",
      tableHeaders: ["Nom", "Finalité", "Durée", "Type"],
      rows: [
        { name: "purple-events-cookie-notice", purpose: "Mémoriser la fermeture de l’avis d’information.", duration: "180 jours maximum", type: "Stockage local strictement nécessaire" },
      ],
      infrastructureTitle: "Sécurité et infrastructure",
      infrastructureText: "Le trafic public doit transiter par Cloudflare et l’origine est hébergée chez Hostinger. Ces prestataires peuvent traiter des données techniques nécessaires à l’acheminement, à la sécurité et aux journaux du service. Selon les mécanismes de protection déclenchés, des témoins strictement nécessaires peuvent être utilisés.",
      consentTitle: "Consentement",
      consentText: "Aucun consentement n’est demandé actuellement, car aucune finalité publicitaire ou analytique facultative n’est activée. Si une telle finalité est ajoutée, elle restera bloquée jusqu’à un choix préalable et révocable.",
      controlTitle: "Vos contrôles",
      controlText: "Vous pouvez supprimer le stockage local depuis les réglages de votre navigateur. L’avis réapparaîtra alors lors d’une prochaine visite.",
    },
    legal: {
      eyebrow: "Informations légales",
      title: "Mentions légales",
      publisher: "Éditeur du site",
      labels: { publisher: "Éditeur", form: "Forme / statut", address: "Adresse", registration: "RCS / identification", email: "E-mail", phone: "Téléphone" },
      brand: "Nom commercial : Purple Events — Une initiative Purple Orchid Group.",
      hosting: "Hébergement et sécurité",
      hostingText: "Serveur d’origine : Hostinger. Acheminement DNS, proxy et sécurité périmétrique : Cloudflare.",
      intellectualProperty: "Propriété intellectuelle",
      intellectualPropertyText: "Les textes, éléments graphiques et créations présentés sur ce site ne peuvent être reproduits ou réutilisés sans autorisation, sous réserve des droits de tiers applicables.",
    },
    footer: { privacy: "Confidentialité", cookies: "Cookies", legal: "Mentions légales" },
    notice: {
      label: "Information relative aux cookies",
      text: "Aucun cookie publicitaire ou analytique. Un stockage local strictement nécessaire mémorise seulement la fermeture de cet avis.",
      accept: "Compris",
      details: "En savoir plus",
    },
  },
  en: {
    previewBlocker: "These details must be validated before public launch.",
    back: "Back to home",
    language: "Français",
    languageCode: "FR",
    privacy: {
      eyebrow: "Data protection",
      title: "Privacy policy",
      intro: "This policy describes processing related to purpleevents.fun. It will be updated before any analytics tool, server-side form or new third-party service is enabled.",
      sections: {
        controller: "Data controller",
        data: "Data and purposes",
        legalBasis: "Legal bases",
        recipients: "Recipients",
        retention: "Retention",
        rights: "Your rights",
      },
      dataText: "Depending on the fields completed, the brief contains: event type, location, timeframe, estimated guest count, name, email and message. In local-copy mode, none of this data is transmitted by the website. In email mode, sending is handled by your own email application.",
      legalBasisText: "Requests are processed to answer your enquiry and, where relevant, take pre-contractual steps. Technical security logs rely on the legitimate interest of protecting the service.",
      recipientsText: "Access is limited to authorised Purple Events personnel and, where necessary, technical hosting, security and email providers acting in their respective roles.",
      rightsText: "You may request access, rectification, erasure, restriction or object where these rights apply. You may also lodge a complaint with Luxembourg’s National Commission for Data Protection (CNPD).",
    },
    cookies: {
      eyebrow: "Digital transparency",
      title: "Cookie policy",
      intro: "Purple Events installs no advertising cookie, analytics tool, marketing pixel or embedded social content in this version.",
      tableTitle: "Functional storage in use",
      tableHeaders: ["Name", "Purpose", "Duration", "Type"],
      rows: [
        { name: "purple-events-cookie-notice", purpose: "Remember that the information notice was dismissed.", duration: "Up to 180 days", type: "Strictly necessary local storage" },
      ],
      infrastructureTitle: "Security and infrastructure",
      infrastructureText: "Public traffic is intended to pass through Cloudflare and the origin is hosted by Hostinger. These providers may process technical data required for routing, security and service logs. Depending on triggered protection mechanisms, strictly necessary identifiers may be used.",
      consentTitle: "Consent",
      consentText: "No consent is currently requested because no optional advertising or analytics purpose is enabled. If such a purpose is added, it will remain blocked until a prior and revocable choice is made.",
      controlTitle: "Your controls",
      controlText: "You can remove local storage through your browser settings. The notice will then reappear on a future visit.",
    },
    legal: {
      eyebrow: "Legal information",
      title: "Legal notice",
      publisher: "Website publisher",
      labels: { publisher: "Publisher", form: "Legal form / status", address: "Address", registration: "RCS / official identification", email: "Email", phone: "Phone" },
      brand: "Trading name: Purple Events — A Purple Orchid Group initiative.",
      hosting: "Hosting and security",
      hostingText: "Origin server: Hostinger. DNS routing, proxy and perimeter security: Cloudflare.",
      intellectualProperty: "Intellectual property",
      intellectualPropertyText: "Texts, graphic elements and creations presented on this website may not be reproduced or reused without permission, subject to applicable third-party rights.",
    },
    footer: { privacy: "Privacy", cookies: "Cookies", legal: "Legal notice" },
    notice: {
      label: "Cookie information",
      text: "No advertising or analytics cookies. One strictly necessary local storage item only remembers that this notice was dismissed.",
      accept: "Understood",
      details: "Learn more",
    },
  },
};
