const origin = "https://purpleevents.fun";
const socialImage = `${origin}/images/purple-events-hero-v1.webp`;

const alternates = {
  home: { fr: `${origin}/`, en: `${origin}/en/`, default: `${origin}/` },
  privacy: { fr: `${origin}/confidentialite/`, en: `${origin}/en/privacy/`, default: `${origin}/confidentialite/` },
  cookies: { fr: `${origin}/cookies/`, en: `${origin}/en/cookies/`, default: `${origin}/cookies/` },
  legal: { fr: `${origin}/mentions-legales/`, en: `${origin}/en/legal-notice/`, default: `${origin}/mentions-legales/` },
};

export const pageMeta = {
  homeFr: {
    lang: "fr",
    locale: "fr_BE",
    alternateLocale: "en_GB",
    socialImage,
    socialImageAlt: "Purple Events — direction créative et production événementielle",
    title: "Purple Events | Création & production événementielle",
    description: "Purple Events imagine, coordonne et produit des événements privés, professionnels et de marque, de l’intention créative à l’orchestration du jour J.",
    canonical: alternates.home.fr,
    alternates: alternates.home,
    robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
    type: "WebPage",
  },
  homeEn: {
    lang: "en",
    locale: "en_GB",
    alternateLocale: "fr_BE",
    socialImage,
    socialImageAlt: "Purple Events — creative direction and event production",
    title: "Purple Events | Creative direction & event production",
    description: "Purple Events designs, coordinates and produces private, professional and brand events, from the creative intention to event-day orchestration.",
    canonical: alternates.home.en,
    alternates: alternates.home,
    robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
    type: "WebPage",
  },
  privacyFr: {
    lang: "fr",
    locale: "fr_BE",
    alternateLocale: "en_GB",
    socialImage,
    socialImageAlt: "Purple Events — direction créative et production événementielle",
    title: "Politique de confidentialité | Purple Events",
    description: "Informations sur la protection des données personnelles traitées dans le cadre du site Purple Events.",
    canonical: alternates.privacy.fr,
    alternates: alternates.privacy,
    robots: "noindex, follow",
    type: "WebPage",
  },
  privacyEn: {
    lang: "en",
    locale: "en_GB",
    alternateLocale: "fr_BE",
    socialImage,
    socialImageAlt: "Purple Events — creative direction and event production",
    title: "Privacy policy | Purple Events",
    description: "Information about personal data processed through the Purple Events website.",
    canonical: alternates.privacy.en,
    alternates: alternates.privacy,
    robots: "noindex, follow",
    type: "WebPage",
  },
  cookiesFr: {
    lang: "fr",
    locale: "fr_BE",
    alternateLocale: "en_GB",
    socialImage,
    socialImageAlt: "Purple Events — direction créative et production événementielle",
    title: "Politique relative aux cookies | Purple Events",
    description: "Stockages locaux et technologies strictement nécessaires utilisés par le site Purple Events.",
    canonical: alternates.cookies.fr,
    alternates: alternates.cookies,
    robots: "noindex, follow",
    type: "WebPage",
  },
  cookiesEn: {
    lang: "en",
    locale: "en_GB",
    alternateLocale: "fr_BE",
    socialImage,
    socialImageAlt: "Purple Events — creative direction and event production",
    title: "Cookie policy | Purple Events",
    description: "Local storage and strictly necessary technologies used by the Purple Events website.",
    canonical: alternates.cookies.en,
    alternates: alternates.cookies,
    robots: "noindex, follow",
    type: "WebPage",
  },
  legalFr: {
    lang: "fr",
    locale: "fr_BE",
    alternateLocale: "en_GB",
    socialImage,
    socialImageAlt: "Purple Events — direction créative et production événementielle",
    title: "Mentions légales | Purple Events",
    description: "Identification de l’éditeur et informations légales du site Purple Events.",
    canonical: alternates.legal.fr,
    alternates: alternates.legal,
    robots: "noindex, follow",
    type: "WebPage",
  },
  legalEn: {
    lang: "en",
    locale: "en_GB",
    alternateLocale: "fr_BE",
    socialImage,
    socialImageAlt: "Purple Events — creative direction and event production",
    title: "Legal notice | Purple Events",
    description: "Publisher identification and legal information for the Purple Events website.",
    canonical: alternates.legal.en,
    alternates: alternates.legal,
    robots: "noindex, follow",
    type: "WebPage",
  },
};

export function structuredData(meta) {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${origin}/#organization`,
        name: "Purple Events",
        url: `${origin}/`,
        logo: `${origin}/images/purple-orchid-emblem-v1.webp`,
        parentOrganization: { "@type": "Organization", name: "Purple Orchid Group" },
      },
      {
        "@type": "WebSite",
        "@id": `${origin}/#website`,
        name: "Purple Events",
        url: `${origin}/`,
        publisher: { "@id": `${origin}/#organization` },
        inLanguage: ["fr", "en"],
      },
      {
        "@type": meta.type,
        "@id": `${meta.canonical}#webpage`,
        url: meta.canonical,
        name: meta.title,
        description: meta.description,
        inLanguage: meta.lang,
        isPartOf: { "@type": "WebSite", "@id": `${origin}/#website`, name: "Purple Events", url: `${origin}/` },
        about: { "@id": `${origin}/#organization` },
      },
    ],
  };
}
