name: Lighthouse CI

on:
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Serve dist & run LHCI
        run: |
          npm ci
          npm run build
          npx serve -s dist -l 8080 &
          npx lhci autorun --url=http://127.0.0.1:8080 --chrome-flags="--no-sandbox --headless"
